### ISSUE TITLE
Using resulting file crash Ship of Harkinian

### ISSUE THREAD

**Issue by RedYggdrasil** [xoascf/ZeldaSaveTool#2]
Hello and thanks for the tool !
 
I've build you program in release parameter using Visual studio, no problem the executable is created.

I then load a .sra file of 32 kb, the program seems to read it correctly (correct number of save, current heart) but when I export it I get a "oot_save.sav" of the exact same size (32 KB) and when I try to put it in "ShipOfHarkinian/Save", either in place of "global.sav" or "File1.save", then ShipOfHarkinian simply crash on startup.

target PC Port Rom version is PAL 1.1, original save file was US 1.2.
SoH version is : MacReady Delta (8.0.3)
PC is Windows 11.
There are the logs, I don't know if you still work on this, and if I did things correctly, but there are the logs in case.
[Ship of Harkinian.log](https://github.com/xoascf/ZeldaSaveTool/files/13697248/Ship.of.Harkinian.log)
[SourceAndResult.zip](https://github.com/xoascf/ZeldaSaveTool/files/13697263/SourceAndResult.zip)

**Comment by xoascf** [comment]
Hey there!
You don't need to save it to `oot_save.sav` as `global.sav` or any of the other `.sav` file slots because they use a new JSON format for saving, just save it directly to the SoH root path (where `soh.exe` is located).
It should work that way.

**Comment by RedYggdrasil** [comment]
Hey ! just tested it at root, yep it works there, thanks !
