### ISSUE TITLE
Savefile corrupted.

### ISSUE THREAD

**Issue by stepsbtw** [xoascf/ZeldaSaveTool#5]
Played in Project64, trying to transfer to SOH.
Built the program, converted the save ( resulted in a 32kb file ).

I tried using as file1.sav, (savefile is corrupted message), then tried used as global.sav, crashed.

Am i doing something wrong?

**Comment by xoascf** [comment]
Yes, you should save it under the same name (`oot_save.sav`) in the game directory, not as `file1.sav`. SoH should convert the save file to the new format automatically.

**Comment by stepsbtw** [comment]
oh, that actually solved. i got it all wrong, thanks.
